Repository openpreserve/jhove, pull requests merged in 2018-03, with the labels that each got.

#315 DEV - Development version 1.19.
  jhove-apps/pom.xml
  jhove-bbt/scripts/auto-vagrant-install.xml
  jhove-bbt/scripts/baseline-jhove.sh
  jhove-bbt/scripts/bbt-jhove.sh
  jhove-bbt/scripts/create-1.19-target.sh
  jhove-bbt/scripts/inc/bb-utils.sh
  jhove-bbt/scripts/travis-test.sh
  jhove-core/pom.xml
  jhove-ext-modules/pom.xml
  jhove-installer/pom.xml
  jhove-installer/src/main/izpack/install.xml
  jhove-modules/pom.xml
  pom.xml
Labels: in progress

#300 Housekeeping
  jhove-installer/src/main/izpack/install.xml
  jhove-installer/src/main/scripts/jhove
  jhove-installer/src/main/scripts/jhove-gui
  jhove-installer/src/main/scripts/jhove-gui.bat
  jhove-installer/src/main/scripts/jhove.bat
Labels: ready

#311 DOC: Explain numbers in audit handler output.
  getting-started/index.html
Labels: documentation, ready

#313 Update WAVE docs with changes for 1.20
  modules/wave/index.html
  references/index.html
Labels: documentation, ready

#309 WAVE: Fix parse error in Associated Data List
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/AssocDataListChunk.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/SimpleTextChunk.java
Labels: in progress, ready

#317 FIX - PDF minor version number checking.
  jhove-bbt/scripts/create-1.19-target.sh
  jhove-bbt/scripts/travis-test.sh
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeaderTest.java
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T01_000_minimal.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T01_001_header-invalid-major-version.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T01_002_header-invalid-minor-version.pdf
Labels: ready

#318 FIX - Document catalog type checking
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PdfModuleTest.java
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T02-01_006_document-catalog-wrong-type-key.pdf
Labels: ready

#319 FIX - Test for inconsistent xref for catalog.
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PdfModuleTest.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/TestUtils.java
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T02-01_001_document-catalog-No-document-catalog.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T02-01_002_document-catalog-wrong-object-number.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T02-01_005_document-catalog-type-key-missing.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T02-01_007_document-catalog-type-key-value-pair-missing.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/corruptionOneByteMissing.pdf
Labels: ready

#323 FIX - NISO 1.0 Format Designation
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java
Labels: enhancement

#324 FIX - PDF embedded MIME type detection
  jhove-bbt/scripts/create-1.19-target.sh
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
Labels: bug

#308 WAVE: RF64, extended MIME type support, and bug fixes
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/AESAudioMetadata.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/JhoveBase.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/ModuleBase.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/RAFInputStream.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/WaveModule.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/iff/ChunkHeader.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/CueChunk.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/DataChunk.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/DataSize64Chunk.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FactChunk.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FormatChunk.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/MessageConstants.java
  test-root/corpora/errors/modules/WAVE-hul/bwf-v8-pcm-44khz-8bit-mono-populated.wav
  test-root/corpora/errors/modules/WAVE-hul/rf64-pcm-44khz-8bit-mono-ds64-chunk-missing.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-chunk-id-embedded-space.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-chunk-id-leading-space.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-chunk-id-non-alphanumeric.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-data-chunk-before-fmt.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-data-chunk-missing.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-file-extra-byte.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-fmt-chunk-missing.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-fmt-chunk-multiple.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-truncated-final-chunk.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-truncated-inner-chunk.wav
  test-root/corpora/errors/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-truncated-riff.wav
  test-root/corpora/examples/modules/WAVE-hul/bwf-v0-pcm-44khz-8bit-mono-populated.wav
  test-root/corpora/examples/modules/WAVE-hul/bwf-v1-pcm-44khz-8bit-mono-populated.wav
  test-root/corpora/examples/modules/WAVE-hul/bwf-v2-pcm-44khz-8bit-mono-populated.wav
  test-root/corpora/examples/modules/WAVE-hul/rf64-alaw-44khz-8bit-mono-minimal.wav
  test-root/corpora/examples/modules/WAVE-hul/rf64-float-44khz-32bit-mono-minimal.wav
  test-root/corpora/examples/modules/WAVE-hul/rf64-float-44khz-64bit-mono-minimal.wav
  test-root/corpora/examples/modules/WAVE-hul/rf64-pcm-44khz-8bit-mono-ds64-chunk-unnecessary.wav
  test-root/corpora/examples/modules/WAVE-hul/rf64-pcm-44khz-8bit-mono-minimal.wav
  test-root/corpora/examples/modules/WAVE-hul/rf64-ulaw-44khz-8bit-mono-minimal.wav
  test-root/corpora/examples/modules/WAVE-hul/wf-pcm-44khz-8bit-mono-minimal.wav
  test-root/corpora/examples/modules/WAVE-hul/wfe-pcm-44khz-8bit-mono-minimal.wav
Labels: enhancement, ready

#322 FIX - PDF module, various processing errors
  jhove-bbt/scripts/create-1.19-target.sh
  jhove-bbt/scripts/travis-test.sh
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/MessageConstants.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PageTreeNode.java
  jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/PdfModuleTest.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/TestUtils.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/DocCatTests.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/HeaderTests.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PageTreeTests.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeaderTest.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PdfModuleTest.java
  jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/TestUtils.java
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/T00_000_minimal-valid.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/doc-cat/T02-01_001_document-catalog-No-document-catalog.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/doc-cat/T02-01_002_document-catalog-wrong-object-number.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/doc-cat/T02-01_003_document-catalog-indirecte-pages-reference-missing.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/doc-cat/T02-01_004_document-catalog-incorrect-pages-reference.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/doc-cat/T02-01_005_document-catalog-type-key-missing.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/doc-cat/T02-01_006_document-catalog-wrong-type-key.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/doc-cat/T02-01_007_document-catalog-type-key-value-pair-missing.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/header/T01_001_header-invalid-major-version.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/header/T01_002_header-invalid-minor-version.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/header/T01_003_header-no-minor-version.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/header/T01_004_header_invalid-syntax-no-dash.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/header/T01_005_header-invalid-syntax-replace-char.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/header/T01_006_header-invalid-syntax-no-pdf.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/header/T01_007_header-no-version-info.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_001_no-page-tree-node.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_002_page-tree-kids-links-recursive.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_003_page-tree-different-kids.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_004_page-tree-non-existing-object-as-kid.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_005_page-tree-no-kids.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_006_page-tree-no-type.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_007_page-tree-wrong-count.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_008_page-tree-node-no-count.pdf
  jhove-modules/src/test/resources/edu/harvard/hul/ois/jhove/module/pdf/page-tree/T02-02_009_page-tree-wrong-type.pdf
Labels: in progress, ready

#328 FIX - broken paragraph structure.
  getting-started/index.html
Labels: documentation
