Repository openpreserve/jhove, pull requests merged in 2019-10, with the labels that each got.

#472 Correct encoding of quote and add a unit test
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/HandlerBase.java
  jhove-core/src/test/java/edu/harvard/hul/ois/jhove/HandlerBaseTest.java
Labels: P2, bug

#449 Correct error messages in TIFF module. Fixes #431
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/TiffModule.java
  jhove-modules/tiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/tiff/ErrorMessages.properties
Labels: P2, feature

#486 Update PdfModule.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
Labels: P2, bug

#477 Update : Use one line for each declaration
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/HtmlCharStream.java
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/ParseHtmlTokenManager.java
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/SimpleCharStream.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/Parser.java
Labels: P3, bug

#484 Fixed: Fields shoud be declared at the top of the class
  extramodules/it/eng/jhove/module/odf/ManifestHandler.java
  extramodules/it/eng/jhove/module/odf/MetaHandler.java
  extramodules/it/eng/jhove/module/odf/OdfModule.java
  extramodules/it/eng/jhove/module/png/PngModule.java
  jhove-modules/aiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/aiff/AiffStrings.java
  jhove-modules/gif-hul/src/main/java/edu/harvard/hul/ois/jhove/module/gif/GifStrings.java
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/HtmlSpecialToken.java
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/ParseException.java
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/ParseHtmlTokenManager.java
  jhove-modules/jpeg-hul/src/main/java/edu/harvard/hul/ois/jhove/module/jpeg/JpegStrings.java
  jhove-modules/jpeg2000-hul/src/main/java/edu/harvard/hul/ois/jhove/module/jpeg2000/JP2Strings.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfStrings.java
  jhove-modules/wave-hul/src/main/java/edu/harvard/hul/ois/jhove/module/wave/WaveStrings.java
Labels: P3, bug

#504 Correct test of Rational in mix 2.0 and fixes #502
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java
  jhove-core/src/test/java/edu/harvard/hul/ois/jhove/handler/XmlHandlerTest.java
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/handler/mix20_output3.xml
Labels: P1, bug

#489 New WARC documentation
  modules/gzip/index.html
  modules/warc/index.html
  references/index.html
Labels: P1, feature, hacktoberfest

#505 Fixed: duplicate if statements
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/RFC1766Lang.java
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/HtmlAttributeDesc.java
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/HtmlDocDesc.java
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/html/ParseHtml.java
  jhove-modules/jpeg2000-hul/src/main/java/edu/harvard/hul/ois/jhove/module/Jpeg2000Module.java
  jhove-modules/jpeg2000-hul/src/main/java/edu/harvard/hul/ois/jhove/module/jpeg2000/ContCodestream.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/AProfile.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/NameTreeNode.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/StructureElement.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/X3Profile.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/XProfileBase.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassB.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassG.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassIT.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITBL.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITBLP1.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITBP.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITBPP1.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITBPP2.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITCT.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITCTP1.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITCTP2.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITFP.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITFPP1.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITFPP2.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITHC.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITHCP1.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITHCP2.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITLW.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITLWP1.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITLWP2.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITMPP1.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITMPP2.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITSD.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassITSDP2.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassP.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassR.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileClassY.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileDLF.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileDLFBW.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileDLFColor.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileDLFGray.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileDNGThumb.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileExifIFD.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileExifThumb.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileFXF.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileFXJ.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileFXS.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileGeoTIFF.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfilePhotoshop.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffProfileRFC1314.java
Labels: P3, bug

#501 DOCS: Add missing WAVE-hul chunks and references
  modules/index.html
  modules/wave/index.html
  references/index.html
Labels: P2, feature, hacktoberfest

#495 FEAT - Begun improvement of developer documentation
  _data/navbar.yml
  documentation/index.html
  documentation/logging/index.md
  modules/warc/index.html
Labels: P2, feature, hacktoberfest

#509 FIX - redundant import.
  jhove-modules/aiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/AiffModule.java
Labels: P3, bug

#513 Update gif Error.Message properties for Control Extensions
  jhove-modules/gif-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/gif/ErrorMessages.properties
Labels: P2, feature

#466 Add documentation for EPUB module
  _data/navbar.yml
  modules/third-party/epub/index.html
  modules/third-party/index.html
  references/index.html
Labels: P2, feature, hacktoberfest
