Repository openpreserve/jhove, pull requests merged in 2019-12, with the labels that each got.

#488 Removed redundant JHOVE survey information.
  index.html
Labels: P2, feature, hacktoberfest

#498 FIX - PDF Destination issues
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/Destination.java
Labels: P2, bug

#497 FEAT - SHA-256 checksumming
  jhove-bbt/scripts/bbt-jhove.sh
  jhove-bbt/scripts/create-1.23-target.sh
  jhove-bbt/scripts/mirror-dirs.sh
  jhove-bbt/scripts/process-modules.sh
  jhove-bbt/scripts/travis-test.sh
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/ChecksumType.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/Checksummer.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/JhoveBase.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/ModuleBase.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/NisoImageMetadata.java
  jhove-core/src/main/scripts/jhove.bat
  jhove-core/src/main/scripts/jhove_local_config.bat
  jhove-installer/src/main/scripts/jhove
  jhove-installer/src/main/scripts/jhove-gui
  jhove-installer/src/main/scripts/jhove-gui.bat
  jhove-installer/src/main/scripts/jhove.bat
Labels: P2, feature

#494 Update README.md
  README.md
Labels: P2, feature, hacktoberfest

#496 Add pt-BR translation for XML/HTML error messages
  jhove-modules/html-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/html/ErrorMessages_pt_BR.properties
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages_pt_BR.properties
Labels: P2, feature, hacktoberfest

#493 Add pt-BR translation for AIFF/WAVE error messages
  jhove-modules/aiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/aiff/ErrorMessages_pt_BR.properties
  jhove-modules/aiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/iff/ErrorMessages_pt_BR.properties
  jhove-modules/wave-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/wave/ErrorMessages_pt_BR.properties
Labels: P2, feature, hacktoberfest

#492 Add pt-BR translation for encoding error messages
  jhove-modules/ascii-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/ascii/ErrorMessages_pt_BR.properties
  jhove-modules/utf8-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/utf8/ErrorMessages_pt_BR.properties
Labels: P2, feature, hacktoberfest

#491 Add pt-BR translation for PDF error messages
  jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages_pt_BR.properties
Labels: P2, feature, hacktoberfest

#490 Add pt-BR translation for PNG error messages
  jhove-ext-modules/src/main/resources/ErrorMessages_pt_BR.properties
Labels: P2, feature, hacktoberfest

#547 FIX - Error IDs output by text handler
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java
Labels: P2, bug

#548 FIX - Sub-messages for new JHOVE messages
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/Message.java
Labels: P2, bug

#549 FIX - Handling of empty PDF CreationDate
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
Labels: P1, bug

#461 FEAT - German translation for AIFF module
  jhove-modules/aiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/aiff/ErrorMessages_de.properties
  jhove-modules/aiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/iff/ErrorMessages_de.properties
  jhove-modules/ascii-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/ascii/ErrorMessages_de.properties
  jhove-modules/gif-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/gif/ErrorMessages_de.properties
  jhove-modules/html-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/html/ErrorMessages_de.properties
  jhove-modules/jpeg2000-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/jpeg2000/ErrorMessages_de.properties
  jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages_de.properties
Labels: P2, feature, hacktoberfest

#467 German translation of PDF error messages
  pdf-de.txt
Labels: P2, feature, hacktoberfest

#464 FEAT: German translation for GIF module messages
  jhove-modules/gif-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/gif/ErrorMessages_de.properties
Labels: P2, feature, hacktoberfest

#462 FEAT - German translation for IFF sub-module
  jhove-modules/aiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/iff/ErrorMessages_de.properties
Labels: P2, feature, hacktoberfest

#552 TRANS - French error messages
  jhove-core/src/main/resources/edu/harvard/hul/ois/jhove/ErrorMessages_fr.properties
  jhove-modules/aiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/aiff/ErrorMessages_fr.properties
  jhove-modules/aiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/iff/ErrorMessages_fr.properties
  jhove-modules/ascii-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/ascii/ErrorMessages_fr.properties
  jhove-modules/gif-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/gif/ErrorMessages_fr.properties
  jhove-modules/html-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/html/ErrorMessages_fr.properties
  jhove-modules/jpeg2000-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/jpeg2000/ErrorMessages_fr.properties
  jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages_fr.properties
  jhove-modules/tiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/tiff/ErrorMessages_fr.properties
  jhove-modules/utf8-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/utf8/ErrorMessages_fr.properties
  jhove-modules/wave-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/wave/ErrorMessages_fr.properties
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages_fr.properties
Labels: P2, feature

#550 TRANS - Dutch error messages
  jhove-modules/ascii-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/ascii/ErrorMessages_nl.properties
  jhove-modules/html-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/html/ErrorMessages_nl.properties
  jhove-modules/jpeg2000-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/jpeg2000/ErrorMessages_nl.properties
  jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages_nl.properties
  jhove-modules/tiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/tiff/ErrorMessages_nl.properties
Labels: P2, feature

#551 TRANS - Danish error messages
  jhove-core/src/main/resources/edu/harvard/hul/ois/jhove/ErrorMessages_da.properties
  jhove-modules/ascii-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/ascii/ErrorMessages_da.properties
  jhove-modules/gif-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/gif/ErrorMessages_da.properties
  jhove-modules/html-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/html/ErrorMessages_da.properties
  jhove-modules/jpeg2000-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/jpeg2000/ErrorMessages_da.properties
  jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages_da.properties
  jhove-modules/tiff-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/tiff/ErrorMessages_da.properties
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages_da.properties
Labels: P2, feature

#555 Issue554
  .gitignore
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/NisoImageMetadata.java
  jhove-ext-modules/src/test/java/org/ithaka/portico/jhove/module/EpubModuleTest.java
  jhove-modules/jpeg-hul/src/main/java/edu/harvard/hul/ois/jhove/module/JpegModule.java
  jhove-modules/jpeg-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/jpeg/ErrorMessages.properties
  jhove-modules/wave-hul/src/test/java/edu/harvard/hul/ois/jhove/module/WaveModuleTest.java
Labels: bug

#556 FIX - Distinction between invariant and multi descriptions
  .gitignore
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/NisoImageMetadata.java
  jhove-ext-modules/src/test/java/org/ithaka/portico/jhove/module/EpubModuleTest.java
  jhove-modules/jpeg-hul/src/main/java/edu/harvard/hul/ois/jhove/module/JpegModule.java
  jhove-modules/jpeg-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/jpeg/ErrorMessages.properties
  jhove-modules/wave-hul/src/test/java/edu/harvard/hul/ois/jhove/module/WaveModuleTest.java
Labels: P1, bug
