Repository openpreserve/jhove, pull requests merged in 2019-04, with the labels that each got.

#452 FIX - Updated broken links
  references/index.html
Labels: P2, bug

#451 FIX - Updated the release details on the home page
  index.html
Labels: P1, bug

#446 jHove hack week contribution of @jacobtakema and @samalloing. Fixes #134
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/PngModule.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/BkgdChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/ChrmChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/GamaChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/HistChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/IccpChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/IdatChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/IendChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/IhdrChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/ItxtChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/MessageConstants.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/PNGChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/PNGException.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/PhysChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/PlteChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/SbitChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/SpltChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/SrgbChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/TextChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/TimeChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/TrnsChunk.java
  jhove-ext-modules/src/main/java/com/mcgath/jhove/module/png/ZtxtChunk.java
  jhove-ext-modules/src/main/resources/ErrorMessages.properties
Labels: feature
