Repository openpreserve/jhove, pull requests merged in 2019-03, with the labels that each got.

#427 FIX - XML Module failure when no checksumming
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/ConfigHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/JhoveBase.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/ModuleBase.java
  jhove-installer/src/main/scripts/jhove
  jhove-installer/src/main/scripts/jhove-gui
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/XmlModule.java
Labels: P1, bug

#428 FIX - PDF Indirect Object Message
  jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages.properties
Labels: P1, bug

#394 Generate valid mix10 and mix20 metadata (various values are Rational).
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/RepTreeRoot.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/NisoImageMetadata.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java
  jhove-core/src/test/java/edu/harvard/hul/ois/jhove/handler/XmlHandlerTest.java
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/handler/mix02_output2.xml
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/handler/mix10_output2.xml
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/handler/mix20_output2.xml
  jhove-modules/jpeg-hul/src/main/java/edu/harvard/hul/ois/jhove/module/JpegModule.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/ExifIFD.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffIFD.java
  jhove-modules/tiff-hul/src/test/java/edu/harvard/hul/ois/jhove/module/tiff/TiffIFDTest.java
Labels: bug

#429 Generate valid mix10 and mix20 metadata (various values are Rational).
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/RepTreeRoot.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/NisoImageMetadata.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java
  jhove-core/src/test/java/edu/harvard/hul/ois/jhove/handler/XmlHandlerTest.java
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/handler/mix02_output2.xml
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/handler/mix10_output2.xml
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/handler/mix20_output2.xml
  jhove-modules/jpeg-hul/src/main/java/edu/harvard/hul/ois/jhove/module/JpegModule.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/ExifIFD.java
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffIFD.java
  jhove-modules/tiff-hul/src/test/java/edu/harvard/hul/ois/jhove/module/tiff/TiffIFDTest.java
Labels: P2, bug

#411 Audit handler clean-up and bug fixes
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/AuditHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/audit/AuditCount.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/audit/AuditState.java
Labels: bug
