Repository openpreserve/jhove, pull requests merged in 2022-04, with the labels that each got.

#716 FIX: Open JDK 11 build
  jhove-apps/pom.xml
  jhove-apps/src/main/java/UserHome.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/Jhove.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/JhoveView.java
  jhove-bbt/scripts/bbt-jhove.sh
  jhove-installer/pom.xml
  jhove-installer/src/main/scripts/jhove
  jhove-installer/src/main/scripts/jhove-gui
  jhove-installer/src/main/scripts/jhove-gui.bat
  jhove-installer/src/main/scripts/jhove.bat
  pom.xml
Labels: bug, P1, RC1.26

#717 FIX: Regression tests for PDF and PNG
  jhove-bbt/scripts/bbt-jhove.sh
  jhove-bbt/scripts/create-1.25-target.sh
  test-root/corpora/regression/modules/PDF-hul/issue_358.pdf
  test-root/corpora/regression/modules/PDF-hul/issue_375.pdf
  test-root/corpora/regression/modules/PDF-hul/issue_531.pdf
  test-root/corpora/regression/modules/PNG-gdm/issue_148.png
Labels: feature

#718 FEAT: Basic Github Actions build
  .github/workflows/test-pr.yml
  .travis.yml
Labels: feature, P1, RC1.26

#693 Make the language option of the error messages configurable
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/messages/JhoveMessages.java
  jhove-core/src/test/java/edu/harvard/hul/ois/jhove/messages/JhoveMessagesTest.java
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/messages/ErrorMessages.properties
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/messages/ErrorMessages_da.properties
  jhove-core/src/test/resources/edu/harvard/hul/ois/jhove/messages/ErrorMessages_fr.properties
Labels: P1

#615 Replace += with StringBuilder for whitespace to speed up Tokenizer
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/Tokenizer.java
Labels: feature, P2, RC1.26

#650 Bump EPUBCheck in extension modules from 4.2.2 to 4.2.6
  jhove-ext-modules/pom.xml
  jhove-ext-modules/src/main/java/org/ithaka/portico/jhove/module/epub/JhoveRepInfoReport.java
  jhove-ext-modules/src/test/java/org/ithaka/portico/jhove/module/EpubModuleTest.java
  jhove-ext-modules/src/test/resources/epub/epub3-valid-multimedia.epub
Labels: feature, P2, RC1.26

#665 Fix building measure property
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/RepTreeRoot.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
Labels: bug, P2, RC1.26

#654 Fixes #653, skipping Comment
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/Parser.java
Labels: bug, P2, RC1.26

#673 Fixed German translation of PDF-HUL-18
  jhove-modules/pdf-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/pdf/ErrorMessages_de.properties
Labels: P2, doc, RC1.26

#677 Remove extra "s" from "fonts" in Representation Info
  modules/third-party/epub/index.html
Labels: bug, P3, RC1.26

#633 XML documentation review fixes
  css/jhove.css
  modules/xml/index.html
Labels: doc

#709 Prevent infinite loop in Literal.readUTFLanguageCode()
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/Literal.java
Labels: bug, P2, RC1.26

#663 gif-hul: use ModuleBase#readUnsignedByte to read global color table
  jhove-modules/gif-hul/src/main/java/edu/harvard/hul/ois/jhove/module/GifModule.java
Labels: bug, P2, RC1.26

#691 do not default exif version
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/ExifIFD.java
Labels: bug, P2, RC1.26

#704 Safely exit infinite loops on AProfile.outlinesOK / checkItemOutline
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/AProfile.java
Labels: bug, P2, RC1.26

#622 Ignoring a comment in annotations
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
Labels: bug, P3, RC1.26

#634 XML-hul code review fixes
  jhove-installer/src/main/config/ext-modules/jhove.conf
  jhove-installer/src/main/config/jhove.conf
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/XmlModule.java
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/xml/EntityInfo.java
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/xml/MessageConstants.java
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/xml/XmlDeclStream.java
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/xml/XmlModuleHandler.java
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages.properties
Labels: bug, P2

#623 Added missing codes to GEOGRAPHICS_INDEX
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/GeoTiffStrings.java
Labels: bug, P2

#635 Improve GUI usability
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/AppInfoWindow.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/ConfigWindow.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/InfoWindow.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/JhoveWindow.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/ModuleInfoWindow.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/NoConfAlert.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/PrefsWindow.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/ProgressWindow.java
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/ViewWindow.java
Labels: bug, feature

#731 FIX: ConfigHander tests for other locales.
  jhove-core/src/test/java/edu/harvard/hul/ois/jhove/ConfigHandlerTest.java
  jhove-ext-modules/src/main/java/edu/harvard/hul/ois/jhove/module/gzip/package-info.java
  jhove-ext-modules/src/main/java/edu/harvard/hul/ois/jhove/module/warc/package-info.java
Labels: bug, P1
