Repository openpreserve/jhove, pull requests merged in 2023-01, with the labels that each got.

#811 TEST: Added patch test to codecov.
  .github/workflows/test-pr.yml
  codecov.yml
Labels: feature

#759 PDF: Remove references to defunct PDF/A profile
  modules/pdf/index.html
  references/index.html
Labels: doc

#810 FIX: Reporting PDF encryption for non reference.
  jhove-bbt/scripts/create-1.27-target.sh
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  test-root/corpora/errors/modules/PDF-hul/issue6010_1.pdf
  test-root/corpora/errors/modules/PDF-hul/issue6010_2.pdf
Labels: bug

#819 TEST: Added test file and fix to integration.
  jhove-bbt/scripts/create-1.27-target.sh
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  test-root/corpora/errors/modules/PDF-hul/pdf-hul-73-bug-size-int.pdf
Labels: feature

#820 FIX: Handling of PDF empty string properties
  jhove-bbt/scripts/create-1.27-target.sh
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/Property.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  test-root/corpora/regression/modules/PDF-hul/pdf-hul-94-false-positive.pdf
Labels: bug

#821 DEV: JPEG-hul 1.5.4
  jhove-bbt/scripts/create-1.25-target.sh
  jhove-bbt/scripts/create-1.27-target.sh
  jhove-installer/pom.xml
  jhove-installer/src/main/izpack/install.xml
  jhove-modules/jpeg-hul/pom.xml
  jhove-modules/jpeg-hul/src/main/java/edu/harvard/hul/ois/jhove/module/JpegModule.java
Labels: bug

#822 TEST: Patched test results for #749
  jhove-bbt/scripts/create-1.27-target.sh
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/Parser.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfStream.java
Labels: bug

#825 TEST: Regression tests for empty strings in PDFs.
  jhove-bbt/scripts/create-1.27-target.sh
  test-root/corpora/regression/modules/PDF-hul/null-string-sig-1.pdf
  test-root/corpora/regression/modules/PDF-hul/null-string-sig-2.pdf
  test-root/corpora/regression/modules/PDF-hul/null-string.pdf
Labels: feature
