Repository openpreserve/jhove, pull requests merged in 2024-03, with the labels that each got.

#903 MAINT: Upgrade Maven build
  jhove-apps/pom.xml
  jhove-bbt/scripts/bbt-jhove.sh
  jhove-core/pom.xml
  jhove-ext-modules/pom.xml
  jhove-installer/pom.xml
  jhove-modules/pom.xml
  pom.xml
Labels: dependencies

#905 FIX: Bump ePub -> 1.3 in test audit.
  jhove-bbt/scripts/create-1.29-target.sh
  jhove-ext-modules/pom.xml
  jhove-ext-modules/src/main/java/org/ithaka/portico/jhove/module/EpubModule.java
  jhove-ext-modules/src/main/java/org/ithaka/portico/jhove/module/epub/JhoveRepInfoReport.java
  jhove-ext-modules/src/test/java/org/ithaka/portico/jhove/module/EpubModuleTest.java
  jhove-ext-modules/src/test/java/org/ithaka/portico/jhove/module/epub/JhoveRepInfoReportTest.java
Labels: dependencies

#906 FIX: XML schema integration tests.
  jhove-bbt/scripts/create-1.29-target.sh
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/xml/XmlModuleHandler.java
Labels: dependencies

#886 Re-implement javax.xml.bind.DatatypeConverter.printHexBinary(byte[])
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/Checksummer.java
  jhove-core/src/test/java/edu/harvard/hul/ois/jhove/ChecksummerTest.java
  jhove-modules/pom.xml
  jhove-modules/wave-hul/src/main/java/edu/harvard/hul/ois/jhove/module/wave/BroadcastExtChunk.java
  jhove-modules/wave-hul/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FormatChunk.java
  pom.xml
Labels: feature

#907 MAINT: Fix tests for PR 871
  jhove-bbt/scripts/create-1.29-target.sh
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfStream.java
  test-root/corpora/regression/modules/PDF-hul/pr_871_a.pdf
  test-root/corpora/regression/modules/PDF-hul/pr_871_b.pdf
  test-root/corpora/regression/modules/PDF-hul/pr_871_c.pdf
Labels: bug

#909 MAINT: PDF Module tests for PR 882
  jhove-bbt/scripts/create-1.29-target.sh
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
Labels: bug

#910 FIX: Tests affected by indent change
  jhove-bbt/scripts/create-1.29-target.sh
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java
Labels: bug
