Repository openpreserve/jhove, pull requests merged in 2024-08, with the labels that each got.

#931 FIX: Update the GH Actions upload task
  .github/workflows/test-pr.yml
  jhove-apps/pom.xml
  jhove-bbt/scripts/create-1.30-target.sh
  jhove-bbt/scripts/travis-test.sh
  jhove-installer/pom.xml
  jhove-installer/src/main/izpack/install.xml
  jhove-modules/aiff-hul/pom.xml
  jhove-modules/ascii-hul/pom.xml
  jhove-modules/gif-hul/pom.xml
  jhove-modules/html-hul/pom.xml
  jhove-modules/jpeg-hul/pom.xml
  jhove-modules/jpeg2000-hul/pom.xml
  jhove-modules/pdf-hul/pom.xml
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/pom.xml
  jhove-modules/tiff-hul/pom.xml
  jhove-modules/utf8-hul/pom.xml
  jhove-modules/wave-hul/pom.xml
  jhove-modules/xml-hul/pom.xml
Labels: bug

#932 REL: JHOVE v1.10.1
  .github/workflows/test-pr.yml
  jhove-apps/pom.xml
  jhove-bbt/scripts/create-1.30-target.sh
  jhove-bbt/scripts/travis-test.sh
  jhove-installer/pom.xml
  jhove-installer/src/main/izpack/install.xml
  jhove-modules/aiff-hul/pom.xml
  jhove-modules/ascii-hul/pom.xml
  jhove-modules/gif-hul/pom.xml
  jhove-modules/html-hul/pom.xml
  jhove-modules/jpeg-hul/pom.xml
  jhove-modules/jpeg2000-hul/pom.xml
  jhove-modules/pdf-hul/pom.xml
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/pom.xml
  jhove-modules/tiff-hul/pom.xml
  jhove-modules/utf8-hul/pom.xml
  jhove-modules/wave-hul/pom.xml
  jhove-modules/xml-hul/pom.xml
Labels: bug

#914 Checks the range of the orientation tag to be 1-9, and forces value 9…
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/NisoImageMetadata.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/JsonHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java
Labels: bug, P1

#938 DEV: Development version 1.31
  jhove-apps/pom.xml
  jhove-bbt/scripts/create-1.31-target.sh
  jhove-bbt/scripts/travis-test.sh
  jhove-core/pom.xml
  jhove-ext-modules/pom.xml
  jhove-installer/pom.xml
  jhove-installer/src/main/izpack/install.xml
  jhove-modules/aiff-hul/pom.xml
  jhove-modules/ascii-hul/pom.xml
  jhove-modules/gif-hul/pom.xml
  jhove-modules/html-hul/pom.xml
  jhove-modules/jpeg-hul/pom.xml
  jhove-modules/jpeg2000-hul/pom.xml
  jhove-modules/pdf-hul/pom.xml
  jhove-modules/pom.xml
  jhove-modules/tiff-hul/pom.xml
  jhove-modules/utf8-hul/pom.xml
  jhove-modules/wave-hul/pom.xml
  jhove-modules/xml-hul/pom.xml
  pom.xml
Labels: feature

#921 Fixes unhandled fatal error when EPUB content.opf date is badly formatted.
  jhove-ext-modules/src/main/java/org/ithaka/portico/jhove/module/epub/JhoveRepInfoReport.java
  jhove-ext-modules/src/main/resources/org/ithaka/portico/jhove/module/epub/ErrorMessages.properties
Labels: bug

#915 Display the Tile and Strip information for TIFF files outside Niso info.
  jhove-bbt/scripts/create-1.30-target.sh
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffIFD.java
Labels: bug, P1

#939 Display the Tile and Strip information for TIFF files outside Niso info.
  jhove-bbt/scripts/create-1.30-target.sh
  jhove-bbt/scripts/create-1.31-target.sh
  jhove-modules/tiff-hul/src/main/java/edu/harvard/hul/ois/jhove/module/tiff/TiffIFD.java
Labels: feature

#941 FIX: XHTML DTD detection
  jhove-bbt/scripts/create-1.31-target.sh
  jhove-modules/html-hul/src/main/java/edu/harvard/hul/ois/jhove/module/HtmlModule.java
Labels: bug

#942 FIX: PDF v2 date parsing
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/Literal.java
  jhove-modules/pdf-hul/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/LiteralTests.java
Labels: bug

#943 FIX: Revert XML SAXParseException reporting
  jhove-bbt/scripts/create-1.28-target.sh
  jhove-bbt/scripts/create-1.31-target.sh
  jhove-modules/jpeg-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/jpeg/ErrorMessages_nl.properties
  jhove-modules/jpeg-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/jpeg/ErrorMessages_sv.properties
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/XmlModule.java
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/xml/MessageConstants.java
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/xml/XmlModuleHandler.java
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages.properties
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages_da.properties
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages_en.properties
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages_fr.properties
  jhove-modules/xml-hul/src/main/resources/edu/harvard/hul/ois/jhove/module/xml/ErrorMessages_pt_BR.properties
Labels: bug

#944 FEAT: Updated audio outputs to conform to the AES57-2011 spec
  jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/RepTreeRoot.java
  jhove-bbt/scripts/create-1.31-target.sh
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/AESAudioMetadata.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/JsonHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java
  jhove-core/src/test/java/edu/harvard/hul/ois/jhove/handler/JsonHandlerTest.java
Labels: feature

#945 FIX: Assorted XML issues
  jhove-bbt/scripts/create-1.31-target.sh
  jhove-core/src/main/java/edu/harvard/hul/ois/jhove/Message.java
  jhove-modules/xml-hul/src/main/java/edu/harvard/hul/ois/jhove/module/xml/XmlModuleHandler.java
  test-root/corpora/errors/modules/XML-hul/0003.xml
  test-root/corpora/errors/modules/XML-hul/12745764.xml
Labels: bug

#946 FIX: PDF Message offsets
  jhove-bbt/scripts/create-1.31-target.sh
  jhove-modules/pdf-hul/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java
  test-root/corpora/errors/modules/HTML-hul/xhtml-1-1-no-xml-dec.html
  test-root/corpora/errors/modules/HTML-hul/xhtml-1-1-xml-dec.html
  test-root/corpora/errors/modules/HTML-hul/xhtml-frames-no-xml-dec.html
  test-root/corpora/errors/modules/HTML-hul/xhtml-frames-xml-dec.html
  test-root/corpora/errors/modules/HTML-hul/xhtml-strict-no-xml-dec.html
  test-root/corpora/errors/modules/HTML-hul/xhtml-strict-xml-dec.html
  test-root/corpora/errors/modules/HTML-hul/xhtml-trans-no-xml-dec.html
  test-root/corpora/errors/modules/HTML-hul/xhtml-trans-xml-dec.html
  test-root/corpora/regression/modules/JPEG-hul/19_e190014.jpg
Labels: bug

#951 FIX: UTF-8 module bump
  docs/index.html
  jhove-installer/pom.xml
  jhove-modules/utf8-hul/pom.xml
  jhove-modules/xml-hul/pom.xml
Labels: bug
